### ISSUE TITLE
Grammar packer / Decoder unable to parse 'german' feature values

### ISSUE THREAD

**Issue by fhieber** [joshua-decoder/joshua#185] opened 2015-02-22 19:09 UTC
I was having trouble running the pipeline script end-to-end on my Macbook (German regional settings). It seems that Thrax is serializing feature values of rules using the number format as given by the JDK, i.e. the system locale (in my case DE). However, later steps such as grammar filtering or decoding fail when loading such grammars, since they cannot parse 'German' float formats: 1,2 instead of 1.2.

I am not sure what the desired behavior of the framework should be, but I would suggest making sure that all parts write floats in standard english format (1.12345).

**Comment by mjpost** [comment] 2015-02-23 13:55
Thanks for reporting this! @jganitkevitch and @jweese, do you have any notion of how involved of a fix this is?

**Comment by jganitkevitch** [comment] 2015-02-23 16:29
I'll look into it.

**Comment by mjpost** [comment] 2015-03-06 04:17
Any luck?

**Comment by jganitkevitch** [comment] 2015-03-06 23:21
I can't reproduce the behavior (with Terminal locale set to de_DE.UTF-8 it
still writes English-format numbers), but I do have what I think is a fix,
which is just forcing the value writing to be done with en_US.

How you want to do this? My Thrax branch (as usual) has a ton of other
stuff in it that's mostly pertaining to paraphrases, tools, and signature
extraction. It's probably worth pulling (and writing some documentation
for), but the fix for this is just the very last commit on my fork.

**Comment by mjpost** [comment] 2015-03-09 02:58
Can you add this patch as a hotfix off master, then merge master into your branch?

**Comment by mjpost** [comment] 2015-10-16 15:12
Are there any updates on this, @fhieber? Trying to close things down for the 6.0.5 release.

**Comment by fhieber** [comment] 2015-10-17 09:14
No updates from my side. Can be closed.

**Comment by mjpost** [comment] 2015-10-17 16:47
Assuming this is fixed, though, right?

**Comment by fhieber** [comment] 2015-10-18 07:00
Not sure if the code changed in this regard but I did not come across the problem again.

**Closed** 2015-10-18 13:02 UTC
